### ISSUE TITLE
On NAS Part of Your Proposed Method

### ISSUE THREAD

**Issue by JackieZhai** [sunsmarterjie/SDL-Skeleton#2]
Could you please opensource the NAS part (the evolution algorithm) of your training procedure? I do not find out in recent version of SDL-Skeleton. It will help me a lot!

**Comment by sunsmarterjie** [comment]
I will update the code of the NAS part after our paper is accepted. If you have any questions, please contact me by email. tianyunjie19@mails.ucas.ac.cn

**Comment by JackieZhai** [comment]
Thank you! I will contact you very soon via e-mail.

**Comment by ofirkris** [comment]
Hello, has the paper been accepted?
Can you opensource the NAS part?
