### ISSUE TITLE
Problems Accessing Baidu's Pre-Trained Model Outside of China

### ISSUE THREAD

**Issue by kongeun3** [sunsmarterjie/SDL-Skeleton#24]
Hello, I have a problem with not being able to access the pre-trained model file of Ada-LSN that you put on Baidu.
If possible, could you please upload a Google Drive link to that file?

problem link: https://pan.baidu.com/s/1ttZYHpmnbeRAcQd7wGAe6g

**Comment by sunsmarterjie** [comment]
https://drive.google.com/file/d/1mWbR-MGcM_8APo5dWJZxSbXhJSUZvAW_/view?usp=sharing
