### ISSUE TITLE
memory leak during training

### ISSUE THREAD

**Issue by Tcorpion** [sunsmarterjie/SDL-Skeleton#6]
Without modifying any codes, I just downloaded the datasets and started training:

`python train_AdaLSN.py   --data1 /home/zyl/FastData/sk1491   --data2 /home/zyl/FastData/sk1491/aug_data/train_pair.lst `

The GPU memory usage growed slowly during training, finally threw `CUDA out of memory. Tried to allocate 20.00 MiB`.

Even I change the the input value of iter_size from 10 to 8, this still happened.

**Comment by sunsmarterjie** [comment]
What is your GPU memory capacity? I train my model with 24G memory.

**Comment by Tcorpion** [comment]
2080Ti, 11GB,  and the inputs are as bellow:
```
python train_AdaLSN.py  \
  --data1 /home/zyl/FastData/sk1491 \
  --data2 /home/zyl/FastData/sk1491/aug_data/train_pair.lst \
  --C 32
```

`CUDA out of memory` happens after 3200 iters.

**Comment by sunsmarterjie** [comment]
You can try to decrease the channel number of the decoder part.

**Comment by Tcorpion** [comment]
@sunsmarterjie Changing the channel number only help reduce memory usage, however do not fix gpu memory leak, I change the loss.backward() logic and it runs OK.

**Comment by Tcorpion** [comment]
With above update, it runs successfully on 2070-GPU (8GB)

**Comment by sunsmarterjie** [comment]
Thanks for your efforts. Could you share the 'update' in this issue?

**Comment by Tcorpion** [comment]
The code and pull request refer to https://github.com/sunsmarterjie/SDL-Skeleton/pull/7 which contains my update.
